# Generated by Django 4.0.2 on 2022-03-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0002_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
